apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault-secrets-operator.fullname" . }}
  labels:
{{ include "vault-secrets-operator.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8383
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 8686
      targetPort: opmetrics
      protocol: TCP
      name: opmetrics
  selector:
    app.kubernetes.io/name: {{ include "vault-secrets-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
