apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault-secrets-operator.fullname" . }}
  labels:
{{ include "vault-secrets-operator.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.operatorMetricsPort }}
      targetPort: opmetrics
      protocol: TCP
      name: opmetrics
  selector:
    app.kubernetes.io/name: {{ include "vault-secrets-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
