{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "vault-secrets-operator.serviceAccountName" . }}
  labels:
{{ include "vault-secrets-operator.labels" . | indent 4 }}
{{ end }}
