apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-secrets-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-secrets-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: vault-secrets-operator
