apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-secrets-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vault-secrets-operator
  template:
    metadata:
      labels:
        name: vault-secrets-operator
    spec:
      serviceAccountName: vault-secrets-operator
      containers:
        - name: vault-secrets-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - vault-secrets-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "vault-secrets-operator"
