kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-secrets-operator
subjects:
- kind: ServiceAccount
  name: vault-secrets-operator
roleRef:
  kind: ClusterRole
  name: vault-secrets-operator
  apiGroup: rbac.authorization.k8s.io
