name: Docker

on: push

jobs:
  docker:
    name: Release Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build Docker Image
        run: make docker-build

      - name: Login to Docker Hub
        if: startsWith(github.ref, 'refs/tags/')
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Package Registry
        if: startsWith(github.ref, 'refs/tags/')
        run: docker login docker.pkg.github.com --username ricoberger --password ${{ secrets.TOKEN }}

      - name: Push Docker Image
        if: startsWith(github.ref, 'refs/tags/')
        run: make docker-push
