name: Docker
on: [release]
jobs:
  build-release:
    name: Release Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Set up Operator SDK v0.10.0
      run: curl -OJL https://github.com/operator-framework/operator-sdk/releases/download/v0.10.0/operator-sdk-v0.10.0-x86_64-linux-gnu && sudo install -m 755 operator-sdk-v0.10.0-x86_64-linux-gnu /usr/local/bin/operator-sdk

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Login to Docker
      run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

    - name: Release
      run: make release
